content:
  - name: "Page"
    label: "Home Page"
    path: "src/pageFiles/home.md"
    type: "file"
    fields:
      - name: tweet
        label: Tweet
        type: text
        options:
          maxlength: 140
  - name: "Page"
    label: "About"
    path: "src/pageFiles/about.md"
    type: "file"
    fields:
      - name: yolo
        label: Yolo
        type: text
        options:
          maxlength: 140
