content:
  - name: "Page"
    label: "Home Page"
    path: "src/pageFiles/home.md"
    type: "file"
    fields:
      - name: title
        label: Title
        type: text

  - name: "Page"
    label: "About"
    path: "src/pageFiles/about.md"
    type: "file"
    fields:
      - name: title
        label: Title
        type: text
      - name: description
        label: Description
        type: rich-text
