pages:
  - name: Home
    path: /
    template: home
  - name: About
    path: /about
    template: about
  - name: Contact
    path: /contact
    template: contact

templates:
  - name: home
    fields:
      - name: title
        type: text
      - name: content
        type: markdown
  - name: about
    fields:
      - name: title
        type: text
      - name: content
        type: markdown
  - name: contact
    fields:
      - name: title
        type: text
      - name: content
        type: markdown
