content:
  - name: "Pages"
    label: "home section"
    path: "src/app"
    type: "collection"
    fields:
      - name: tweet
        label: Tweet
        type: text
        options:
          maxlength: 140
  - name: "Page"
    label: "home section"
    path: "src/app"
    type: "file"
    fields:
      - name: yolo
        label: Yolo
        type: text
        options:
          maxlength: 140
