content:
  - name: "page"
    label: "Home Page"
    path: "src/pageFiles/home.md"
    type: "file"
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: text

  - name: "about"
    label: "About"
    path: "src/pageFiles/about.md"
    type: "file"
    view:
      fields: [ title, description ]
    fields:
      - name: title
        label: Title
        type: text
      - name: description
        label: Description
        type: rich-text
