# Website configuration
title: Your Website Title
description: A brief description of your website
url: https://your-website-domain.com
author: Your Name
email: your@email.com

# Theme configuration
theme: default # Change this to the theme you want to use
theme_config:
  # Theme specific configuration options go here

# Navigation menu configuration
menu:
  - name: Home
    link: "/"
  - name: About
    link: "/about"

# Content configuration
content:
  # Home page content
  home:
    title: Home Page Title
  # About page content
  about:
    title: About Page Title
    content: Your website's about content goes here.