content:
  - name: "Home"
    label: "home section"
    path: "src/page"
    type: "page"
    fields:
      - name: tweet
        label: Tweet
        type: text
        options:
        maxlength: 140
